# Generated by Django 5.0.8 on 2024-08-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
