# Generated by Django 5.0.8 on 2024-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
